---
name: "Cachix"
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        id: cachix-with-tags
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: tguimbert
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: cachix/cachix-action@v12
        if: steps.cachix-with-tags.conclusion == 'skipped'
        with:
          name: tguimbert
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Build NixOs configuration
        run: nix build .
